### PR TITLE
perf(account-creation): fixed several bottlenecks, slowing the page down

### LINKED ISSUE #118: refactor(profile-creation): the steps for creating a profile feel "laggy"
While creating a new profile in dev mode, the form feels laggy and the inputs are delayed. Maybe caused by some `useEffect` or `useState`

CC @BenedictHomuth

### PR DESCRIPTION
**Pull request by BenedictHomuth**
# ⚡ Profile Creation Performance Optimizations

This PR addresses the UI lag and input delays experienced during the profile creation process, as described in (#118). The bottleneck was primarily caused by expensive calculations and heavy re-renders being triggered on every keystroke.

### 1. 🌍 Memoized Country List and Currency Lookup (`StepOne.tsx`)

*   **❌ Problem:** The entire list of ~250 countries was being re-translated and re-sorted on every single character typed into any field.
*   **✅ Solution:** Wrapped the country list generation and the currency symbol lookup in `useMemo`.
*   **🚀 Impact:** Massive reduction in CPU cycles during typing. The heavy operation now only runs once or when the language changes.

### 2. 🎨 Memoized Color Swatches (`StepTwo.tsx`)

*   **❌ Problem:** The theme color mapping logic was being re-processed during every render of the profile creation flow, even when the user was on a different step.
*   **✅ Solution:** Wrapped the color swatch generation in `useMemo`.
*   **🚀 Impact:** Ensures Step 2 remains fluid and prevents its rendering logic from interfering with the performance of Step 1.

### 3. 📝 Optimized Form Validation Strategy (`index.tsx`)

*   **❌ Problem:** Calling `form.isValid()` in the top-level render body forced the form library to execute all validation rules on every keystroke.
*   **✅ Solution:** Removed the continuous `isValid()` check. Switched to "on-demand" validation using `form.validate()` within the `validateAndGoToNextPage` and `handleSubmit` handlers.
*   **🚀 Impact:** Eliminated unnecessary validation overhead during typing while ensuring the form remains strictly validated before submission.

## 🏁 Conclusion

These optimizations significantly reduce the main thread workload, resulting in a snappy and responsive UI. Input latency is resolved, and the overall user experience during profile setup is much smoother.

### CODE REVIEW

**Review by timderes — CHANGES_REQUESTED** [review]
In my opinion, these are good changes. But they do not fix the performance issues on my end.

**Comment by BenedictHomuth** [comment]
Should we still merge this? Looks very out of date by now?!

**Comment by timderes** [comment]
It’s quite old, but the profile creation hasn’t been updated since you opened this PR

**Comment by BenedictHomuth** [comment]
In that case, you may give it one more look, if things look aligned and merge it :)

**Comment by timderes** [comment]
Yes 😄 I may have encountered the same issue while working on open slalom. It’s related to Mantine’s [controlled vs. uncontrolled](https://mantine.dev/form/uncontrolled/)  form modes. So it’s probably not actually a performance problem. The page simply doesn’t re-render on every input change

But the memoization (`useMemo`) changes definitely won’t hurt.

File: renderer/components/content/profileCreation/StepTwo.tsx [hunk 1]
```diff
@@ -19,19 +20,22 @@ const StepTwo = ({
...
+          style={{ cursor: "pointer" }}
+          onClick={() => form.setValues({ color })}
+        >
+          {color === form.values.color ? (
+            <CheckIcon width={15} style={{ color: theme.white }} />
+          ) : null}
+        </ColorSwatch>
+      </Tooltip>
+    ));
+  }, [theme.colors, theme.white, t, form.values.color]);
```
Comment (timderes) [inline renderer/components/content/profileCreation/StepTwo.tsx:38]: Not sure about the `theme.white` here. But i think it wont hurt?! :D

**Comment by timderes** [comment]
So I tried both `controlled` and `uncontrolled`, but it didn’t improve the performance. I’ve been thinking that the problem might be that we’re re-rendering all three steps. Would you like to look into this, or do you have any other ideas, @BenedictHomuth?

If you use the production build, it works quite well. So perhaps we can merge this here first

**Review by timderes — APPROVED** [review]
